### ISSUE TITLE
'DefaultLogger' object has no attribute 'log_artifact'

### ISSUE THREAD

**Issue by hsiaotung-tan** [BehnoodRasti/HySUPP#3]
'DefaultLogger' object has no attribute 'log_artifact'
how can I change the defaultLogger in config.yaml?

**Comment by azouaoui-cv** [comment]
Hello @hsiaotung-tan,
I assume you are confused with the two existing loggers.
One originates from `mlxp` and provides the `log_artifact` method while the more generic logger (a `DefaultLogger`) object inherits from the base logger (`logging.getLogger(__name__)`).

Could you provide a sample of your code where the error occurs?

**Comment by hsiaotung-tan** [comment]
I found the reason.
The code you provided is built on top of `MLXP==0.1.0`. And my local environment is `MXLP==1.0.0`. there is a difference in the logging code between the two versions.

**Comment by azouaoui-cv** [comment]
My explanation was indeed flawed.
Glad you found the reason.
In the future we will bump the requirements to MLXP 1.0.0.
